---

env:
  es6: true
  node: true

overrides:
  -
    files:
      - '*.js'
    extends:
      - '@matthiaskunnen/eslint-config-base'

  -
    files:
      - 'spec/**/*.ts'
    extends:
      - '@matthiaskunnen/eslint-config-typescript'
      - 'plugin:ava/recommended'

    parser: '@typescript-eslint/parser'

    parserOptions:
      project:
        - tsconfig/tsconfig.lint.json
      sourceType: module

    plugins:
      - 'eslint-plugin-ava'

    rules:
      '@typescript-eslint/no-use-before-define': off
      ava/no-ignored-test-files: off # The files are included, eslint just doesn't know it
      func-names: off

  -
    files:
      - 'src/**/*.ts'
    extends:
      - '@matthiaskunnen/eslint-config-typescript'

    parser: '@typescript-eslint/parser'

    parserOptions:
      project:
        - tsconfig/tsconfig.lint.json
      sourceType: module

    rules:
      "@typescript-eslint/ban-types":
        - error
        -
          types:
            Function: false
            Object: false
