name: Node CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn run build
    - name: Lint
      run: yarn run lint
    - name: Test + coverage
      run: yarn run coverage # This also runs tests
    - name: Test TypeScript
      run: yarn run test:ts
    - name: Test diagnostics
      run: yarn run test:diagnostics
    - name: Upload coverage
      uses: codecov/codecov-action@v1.3.1
      with:
        files: ./coverage/lcov.info
    - name: Determine size
      run: yarn run size
